config/routes.rb
Rails.application.routes.draw do
  get 'user_profile/show'

  devise_for :users, :controllers => {registrations: 'registrations'}

post 'courses/:id/enroll', to: 'courses#enroll', as: :enroll

  resources :course_details
  resources :courses 

  resources :categories do
    resources :courses
  end

  devise_scope :user do
    get 'sign_up' , to: 'registrations#new', as: :sign_up
    get 'login' , to: 'devise/sessions#new' , as: :login
    get 'logout' , to: 'devise/sessions#destroy' , as: :logout
  end

  root to: 'categories#index'

  get 'profile', to: 'user_profile#show'

end

app/models/course_detail.rb
class CourseDetail < ActiveRecord::Base
	belongs_to :course
end

app/controllers/course_details_controller.rb
class CourseDetailsController < ApplicationController
  before_action :set_course_detail, only: [:show, :edit, :update, :destroy]

  # GET /course_details
  # GET /course_details.json
  def index
    @course_details = CourseDetail.all
  end

  # GET /course_details/1
  # GET /course_details/1.json
  def show
  end

  # GET /course_details/new
  def new
    @course_detail = CourseDetail.new
  end

  # GET /course_details/1/edit
  def edit
  end

  # POST /course_details
  # POST /course_details.json
  def create
    @course_detail = CourseDetail.new(course_detail_params)

    respond_to do |format|
      if @course_detail.save
        format.html { redirect_to @course_detail, notice: 'Course detail was successfully created.' }
        format.json { render :show, status: :created, location: @course_detail }
      else
        format.html { render :new }
        format.json { render json: @course_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_details/1
  # PATCH/PUT /course_details/1.json
  def update
    respond_to do |format|
      if @course_detail.update(course_detail_params)
        format.html { redirect_to @course_detail, notice: 'Course detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @course_detail }
      else
        format.html { render :edit }
        format.json { render json: @course_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_details/1
  # DELETE /course_details/1.json
  def destroy
    @course_detail.destroy
    respond_to do |format|
      format.html { redirect_to course_details_url, notice: 'Course detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_detail
      @course_detail = CourseDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_detail_params
      params.require(:course_detail).permit(:course_description, :syllabus, :recommended_background, :course_format, :course_id)
    end
end

app/helpers/course_details_helper.rb
module CourseDetailsHelper
end

app/views/course_details/_form.html.erb
<%= simple_form_for(@course_detail, htlml: {class: 'form-horizontal'}, wrapper: :horizontal_form) do |f| %>
  <% if @course_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course_detail.errors.count, "error") %> prohibited this course_detail from being saved:</h2>

      <ul>
      <% @course_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :course_description %><br />
   
  </div>
  <div class="field">
    <%= f.input :syllabus %><br />
    
  </div>
  <div class="field">
    <%= f.input :recommended_background %><br />
    
  </div>
  <div class="field">
    <%= f.input :course_format %><br />
    
  </div>
  <div class="field">
    <%= f.input :course_id, collection: Course.all%><br>
    
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/course_details/edit.html.erb
<h1>Editing course_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @course_detail %> |
<%= link_to 'Back', course_details_path %>

app/views/course_details/index.html.erb
<h1>Listing course_details</h1>

<table>
  <thead>
    <tr>
      <th>Course description</th>
      <th>Syllabus</th>
      <th>Recommended background</th>
      <th>Course format</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_details.each do |course_detail| %>
      <tr>
        <td><%= course_detail.course_description %></td>
        <td><%= course_detail.syllabus %></td>
        <td><%= course_detail.recommended_background %></td>
        <td><%= course_detail.course_format %></td>
        <td><%= course_detail.course_id %></td>
        <td><%= link_to 'Show', course_detail %></td>
        <td><%= link_to 'Edit', edit_course_detail_path(course_detail) %></td>
        <td><%= link_to 'Destroy', course_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course detail', new_course_detail_path %>

app/views/course_details/new.html.erb
<h1>New course_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', course_details_path %>

app/views/course_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course description:</strong>
  <%= @course_detail.course_description %>
</p>

<p>
  <strong>Syllabus:</strong>
  <%= @course_detail.syllabus %>
</p>

<p>
  <strong>Recommended background:</strong>
  <%= @course_detail.recommended_background %>
</p>

<p>
  <strong>Course format:</strong>
  <%= @course_detail.course_format %>
</p>

<p>
  <strong>Course:</strong>
  <%= @course_detail.course_id %>
</p>

<%= link_to 'Edit', edit_course_detail_path(@course_detail) %> |
<%= link_to 'Back', course_details_path %>