config/routes.rb
Rails.application.routes.draw do
  get 'user_profile/show'

  devise_for :users, :controllers => {registrations: 'registrations'}

post 'courses/:id/enroll', to: 'courses#enroll', as: :enroll

  resources :course_details
  resources :courses 

  resources :categories do
    resources :courses
  end

  devise_scope :user do
    get 'sign_up' , to: 'registrations#new', as: :sign_up
    get 'login' , to: 'devise/sessions#new' , as: :login
    get 'logout' , to: 'devise/sessions#destroy' , as: :logout
  end

  root to: 'categories#index'

  get 'profile', to: 'user_profile#show'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy, :enroll]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  def enroll
    @user = User.find(current_user.id)
    @enrollment = @user.enrollments.create(course: @course)
    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @course, notice: 'Successfully Signed up for this Course.' }
        format.json { render :show, status: :created, location: @course }
        format.js #calls create.js.erb
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /courses
  # POST /courses.json
  def create
    #@course = Course.new(course_params)
    @category = Category.find(params[:category_id])
    @course = @category.courses.create(course_params)
    respond_to do |format|
      if @course.save
        format.html { redirect_to @category, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
        format.js #calls create.js.erb
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :short_desc, :duration, :language, :category_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<%= div_for course do %>
		<p>
			#<strong>Posted-test <%= time_ago_in_words(course.created_at) %></strong><br />
			<%= h(course.name)	%> <br/>
			<%= course.short_desc%> <br/>
			<%= course.duration%> </br/>
			<%= course.language%>
		</p>
<% end %>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short_desc %><br>
    <%= f.text_area :short_desc %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/create.js.erb
var new_course = $("<%= escape_javascript(render(:partial =>  @course)) %>").hide();
$('#courses').prepend(new_course);
$('#course_<%= @course.id %>').fadeIn('slow');
$('#new_course')[0].reset();

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short desc</th>
      <th>Duration</th>
      <th>Language</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.short_desc %></td>
        <td><%= course.duration %></td>
        <td><%= course.language %></td>
        <td><%= course.category_id %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= button_to 'Enroll', enroll_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Short desc:</strong>
  <%= @course.short_desc %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @course.duration %>
</p>

<p>
  <strong>Language:</strong>
  <%= @course.language %>
</p>

<p>
  <strong>Category:</strong>
  <%= @course.category_id %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>