config/routes.rb
Rails.application.routes.draw do
  get 'user_profile/show'

  devise_for :users, :controllers => {registrations: 'registrations'}

post 'courses/:id/enroll', to: 'courses#enroll', as: :enroll

  resources :course_details
  resources :courses 

  resources :categories do
    resources :courses
  end

  devise_scope :user do
    get 'sign_up' , to: 'registrations#new', as: :sign_up
    get 'login' , to: 'devise/sessions#new' , as: :login
    get 'logout' , to: 'devise/sessions#destroy' , as: :logout
  end

  root to: 'categories#index'

  get 'profile', to: 'user_profile#show'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpiritualUniversity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<!-- NAVBAR
================================================== -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Brand</a>
        </div>
         <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse">

              <ul class="nav navbar-nav">
                  <li> <%=link_to "All Courses", categories_path %> </li>

              </ul>
              <ul class="nav pull-right">
                
                  <% if user_signed_in? %>
                      <li><%= link_to current_user.full_name , edit_user_registration_path%> </li>
                    <li> <%= link_to "Log Out", logout_path%> </li>
                      
                    <% else %>
                        <li><%= link_to "Sign up", sign_up_path  %></li>
                        <li><%= link_to "Log In", login_path %></li>

                    <% end %>
                
              </ul>
            
        </div>
    </div>
</nav>
    




	
<div class="container">

  <% flash.each do |type, message| %>
    <div class="alert <%= flash_class type%>" role="alert">
        <button class="close" data-dismiss="alert">X</button>
        <%= message %>
    </div>

  <%end%>
	
	<%= yield %>
</div>
</body>
</html>


       